### ISSUE TITLE
Unable to expand abbreviation "!" (basic HTML page) when working on .erb files

### ISSUE THREAD

**Issue by afifsohaili** [emmetio/emmet-atom#112] opened 2014-07-20 22:52 UTC
Trying to expand "!" results in "<!></!>" instead of the basic HTML structure. Only happens when working on .erb files. Expanding "!" into the basic HTML structure works fine when working on .html files.

Mac OS X Mavericks
Atom 0.115.0
##

**Comment by silvenon** [comment] 2015-01-16 13:34
Probably duplicate of #104.

**Closed** 2018-10-19 01:32 UTC
